[application]

[web.app]

# HTML title tag content
title = "cadet-hub"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]
